# factorial-cache-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factorial-ingress
  namespace: factorial
spec:
  rules:
    - http:
        paths:
          # factorial 라는 path 로 요청이 들어오면
          # 해당 요청을 지정된 backend 로 요청을
          # 보내겠다는 의미
          - pathType: Prefix
            # http://localhost/factorial/10
            # http://localhost/factorial/11
            # localhost/factorial/11?key=abcd-1234-5678
            path: /factorial
            backend:
              service:
                name: factorial-cache-service
                port:
                  number: 8080

